site_name: Wrapping AENS names into AEX-141 NFTs
plugins:
  - search
repo_url: 'https://github.com/marc0olo/aens-nfts'
edit_uri: 'https://github.com/marc0olo/aens-nfts'

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - ideation-mindmap.md
  - Sequence Diagrams:
    - Selected actions:
      - diagrams/wrap_aens_names.md
      - diagrams/update_pointers.md
      - diagrams/revoke_aens_names.md
      - diagrams/transfer_aens_names.md
      - diagrams/unwrap_aens_names.md
      - diagrams/reward_users.md
      - diagrams/extend_aens_names.md
      - diagrams/transfer_nfts.md
      - diagrams/burn_nfts.md
    - diagrams/full-example-sequence.md
  - sponsors.md