version: '3.6'
services:

  aeproject_node:
    image: marc0olo/aeternity:verify_sig-devmode ## TODO replace with official bundle that has latest features
    hostname: node
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    volumes:
      - './docker/aeternity.yaml:/home/aeternity/aeternity.yaml'
      - './docker/accounts.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json'

  aeproject_compiler:
    image: aeternity/aesophia_http:v7.6.0
    hostname: compiler
    ports:
      - '3080:3080'

  aeproject_proxy:
    image: nginx:latest
    hostname: proxy
    ports:
      - '3001:3001'
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'

  compiler_ceres:
    image: marc0olo/aesophia_http:v8.0.0-ceres ## TODO replace with official compiler release v8
    hostname: compiler-ceres
    ports:
      - '3081:3080'