name: Smart Contract Tests
on: [push]

defaults:
  run:
    working-directory: ./development/smart-contracts

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm ci
      - run: npx aeproject env && sleep 3
      - run: npm run test:iris
      - run: npm run test:ceres